batch_size: 128
classes_num: 100
dataset_name: cifar100
dataset_path: data/
device: cuda
embedding_size: 1024
encoder_blocks_num: 16
epoch: 200
heads_num: 16
load_from: null
load_model_config: false
patch_size: 16
save_dir: checkpoints/
save_interval: 1
test: false
use_cnn_embedding: false
